# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = 采集器上位机
DESTDIR = ./x64/Debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(采集器上位机.pri)

DISTFILES += \
    采集器上位机.pri

RESOURCES += \
    Welcom.qrc

FORMS += \
    Welcom.ui \
    choose.ui \
    choose_low.ui \
    dataprocessing.ui

HEADERS += \
    Welcom.h \
    choose.h \
    choose_low.h \
    dataprocessing.h

SOURCES += \
    Welcom.cpp \
    choose.cpp \
    choose_low.cpp \
    dataprocessing.cpp \
    main.cpp
